language: julia

os:
  - osx
  - linux

julia:
  - 1.6
  - 1.7
matrix:
  - PYTHON=Conda-python
env:
  - PYTHON=~/.julia/conda/3/bin/python
before_install:
  - julia -e 'using Pkg; Pkg.add.(["PyCall","Conda"]); Pkg.build("PyCall");using PyCall;println("Python for Julia $(PyCall.python) ver. $(PyCall.pyversion)"); using Conda; Conda.add.(["matplotlib","networkx"]);run(`$(PyCall.python) -m pip install hypernetx`)';


notifications:
  email: false

after_success:
  - julia -e 'using Pkg;cd(Pkg.dir("SimpleHypergraphs")); Pkg.add("Coverage");using Coverage;Coveralls.submit(Coveralls.process_folder())';
  - julia --project=docs/ -e 'if Sys.isapple();exit();end;display(pwd());using Pkg;Pkg.instantiate();Pkg.develop(PackageSpec(path=pwd()));include("docs/make.jl")'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.7
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
